config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'account'
  
  resources :users do
    scope module: 'user' do
      resources :profiles
    end  
  end

  scope module: 'property' do
    resources :commercials
    resources :residentials
    resources :premarkets do
      resources :premarket_styles
    end
  end

  resources :posts

  resources :statics do
    collection do
      get 'homepage'
    end
  end

  root 'statics#homepage'

end

app/models/commercial.rb
class Commercial < ActiveRecord::Base
  belongs_to :commercial_type
  belongs_to :property_post_type
  has_many :property_galleries, as: :imageable
  has_one :property_location, as: :locatable

  accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :property_location

  # Sunspot search function
  searchable do
  	text :title, :description
  	integer :property_post_type_id
  	integer :commercial_type_id
  	double :price
  	double :size
  end
end

app/models/commercial_type.rb
class CommercialType < ActiveRecord::Base
	has_many :commercials
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :post_categorizations
	has_many :post_categories, through: :post_categorizations

	mount_uploader :feature_image, PostFeatureImageUploader

	# Search function
	searchable do 
		text :title, :excerpt, :content
		integer :post_category_ids, :multiple => true
	end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	has_many :post_categorizations
	has_many :posts, through: :post_categorizations
end

app/models/premarket.rb
class Premarket < ActiveRecord::Base
	belongs_to :premarket_type
	
	has_many :premarket_styles, dependent: :destroy
	has_many :property_central_facilities, as: :central_facility
	has_one :property_location, as: :locatable

  accepts_nested_attributes_for :property_location
	accepts_nested_attributes_for :premarket_styles, reject_if: :all_blank, allow_destroy: :true 

	mount_uploader :feature_image, PremarketFeatureImageUploader
end

app/models/premarket_style.rb
class PremarketStyle < ActiveRecord::Base
	belongs_to :premarket

	belongs_to :property_bedroom
	belongs_to :property_bathroom
	belongs_to :property_furnishing_type
	belongs_to :property_pet_friendly_type
	belongs_to :property_parking_space
	has_many :property_private_facilities, as: :private_facility
	has_many :property_furnitures, as: :furniture
	has_many :property_areas, as: :area
	has_many :property_galleries, as: :imageable, dependent: :destroy

	accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true 
end

app/models/premarket_type.rb
class PremarketType < ActiveRecord::Base
	has_one :premarket
end

app/models/property_area.rb
class PropertyArea < ActiveRecord::Base
	belongs_to :area, polymorphic: true
end

app/models/property_bathroom.rb
class PropertyBathroom < ActiveRecord::Base
	has_one :residential
	has_one :premarket_style
end

app/models/property_bedroom.rb
class PropertyBedroom < ActiveRecord::Base
	has_one :residential
	has_one :premarket_style
end

app/models/property_furniture.rb
class PropertyFurniture < ActiveRecord::Base
	belongs_to :furniture, polymorphic: true
end

app/models/property_gallery.rb
class PropertyGallery < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true

	mount_uploader :image, PropertyGalleryUploader
end

app/models/property_location.rb
class PropertyLocation < ActiveRecord::Base
	belongs_to :locatable, polymorphic: true
end

app/models/residential.rb
class Residential < ActiveRecord::Base
  has_many :property_central_facilities, as: :central_facility
  has_many :property_private_facilities, as: :private_facility
  has_many :property_furnitures, as: :furniture
  has_many :property_areas, as: :area
  has_many :property_galleries, as: :imageable
  has_one :property_location, as: :locatable
  belongs_to :property_post_type
  belongs_to :residential_type
  belongs_to :property_bedroom
  belongs_to :property_bathroom
  belongs_to :property_furnishing_type
  belongs_to :property_pet_friendly_type
  belongs_to :property_parking_space

  accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :property_location
  
  # Sunspot search function
  searchable do
    text :title, :description
    integer :residential_type_id 
    integer :property_post_type_id
    integer :property_bedroom_id
    integer :property_bathroom_id
    integer :property_furnishing_type_id
    integer :property_pet_friendly_type_id
    integer :property_parking_space_id
    integer :property_central_facility_ids, :multiple => true
    # integer :private_facility, :multiple => true
    # integer :furniture, :multiple => true
    # integer :area,  :multiple => true
    double :price
    double :size
  end
end

app/models/residential_type.rb
class ResidentialType < ActiveRecord::Base
	has_many :residentials
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile
end

app/models/user_company.rb
class UserCompany < ActiveRecord::Base
  belongs_to :user_profession
end

app/models/user_profession.rb
class UserProfession < ActiveRecord::Base
	belongs_to :user_profile
	has_one :user_company
	belongs_to :user_professional_expertise

	accepts_nested_attributes_for :user_company, reject_if: :all_blank
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user
	has_one :user_profession

	accepts_nested_attributes_for :user_profession, reject_if: :all_blank 
	
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
  before_action :set_profile, except: [:new, :create]
  before_action :authenticate_user!, except: [:show]

  def show
  end

  def new
    @profile = current_user.build_user_profile
    user_profession = @profile.build_user_profession
    user_company = user_profession.build_user_company
  end

  def edit
  end

  def create
    @profile = UserProfile.new(profile_params)
    @profile.id = params[:user_id]
    @profile.user_id = params[:user_id]

    if @profile.save
      redirect_to root_path, notice: 'Profile has been created'
    else
      render :new
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_profile_path, notice: 'Profile has been updated'
    else
      render :edit
    end  
  end

  private

    def set_profile
      @profile = UserProfile.find(params[:id])
    end

    def profile_params
      params.require(:user_profile).permit(
        :first_name,
        :last_name,
        :email,
        :phone,
        :professional,
        :profile_image,
        user_profession_attributes: [
          :user_profile_id,
          :user_professional_expertise_id,
          :about_me,
          user_company_attributes: [
            :user_profession_id,
            :name,
            :website,
            :email,
            :phone,
            :fax,
            :address,
            :street,
            :city,
            :province,
            :country,
            :postal_code,
            :longitude,
            :latitude            
          ]
        ]
      )
    end

end

app/controllers/user/registration_processes_controller.rb
class User::RegistrationProcessesController < ApplicationController
	include Wicked::Wizard

	steps :create_user, :create_personal_profile, :create_company_profile
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_category
		@post_categories = PostCategory.all
	end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/user/profiles_helper.rb
module User::ProfilesHelper
end

app/helpers/user/registration_processes_helper.rb
module User::RegistrationProcessesHelper
end

app/views/user/profiles/_form.html.erb
<%= f.error_notification %>

<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :email %>
<%= f.input :phone %>
<%= f.file_field :profile_image %>
<label>User type</label>
<%= select_tag :professional, options_for_select([['Regular User', 0], ['Agency/Service Provider', 1]], selected: 0) %>

<%= render 'user_profession_form', f: f %>

<%= f.submit %>

app/views/user/profiles/_user_company_form.html.erb
<h1>Company Details</h1>
<%= f.simple_fields_for :user_company do |f| %>
	<%= f.input :name %>
	<%= f.input :website %>
	<%= f.input :email %>
	<%= f.input :phone %>
	<%= f.input :fax %>
	<%= f.input :address %>
	<%= f.input :street %>
	<%= f.input :city %>
	<%= f.input :province %>
	<%= f.input :country %>
	<%= f.input :postal_code %>
<% end %>

app/views/user/profiles/_user_profession_form.html.erb
<h1>Agent Details</h1>
<%= f.simple_fields_for :user_profession do |f| %>
	<%= f.input :user_professional_expertise, as: :select, collection: UserProfessionalExpertise.all %>
	<%= f.input :about_me %>

	<%= render 'user_company_form', f: f %>
<% end %>

app/views/user/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= simple_form_for @profile, url: user_profile_path([@user, current_user], [current_user]) do |f| %>
  <%= f.error_notification %>
  
  <%= render 'form', f: f %>

<% end %>

app/views/user/profiles/new.html.erb
<h1>New Profile</h1>

<%= simple_form_for @profile do |f| %>
  <%= f.error_notification %>
  
  <%= render 'form', f: f %>

<% end %>

app/views/user/profiles/show.html.erb
<%= @profile.first_name %>
<%= @profile.last_name %>
<%= link_to 'Edit Profile', edit_user_profile_path([@user, current_user], [current_user]) %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>