config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'account'
  
  resources :users do
    scope module: 'user' do
      resources :profiles
    end  
  end

  scope module: 'property' do
    resources :commercials
    resources :residentials
    resources :premarkets do
      resources :premarket_styles
    end
  end

  resources :posts

  resources :statics do
    collection do
      get 'homepage'
    end
  end

  root 'statics#homepage'

end

app/models/commercial.rb
class Commercial < ActiveRecord::Base
  belongs_to :commercial_type
  belongs_to :property_post_type
  has_many :property_galleries, as: :imageable
  has_one :property_location, as: :locatable

  accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :property_location

  # Sunspot search function
  searchable do
  	text :title, :description
  	integer :property_post_type_id
  	integer :commercial_type_id
  	double :price
  	double :size
  end
end

app/models/commercial_type.rb
class CommercialType < ActiveRecord::Base
	has_many :commercials
end

app/controllers/property/commercials_controller.rb
class Property::CommercialsController < ApplicationController
  before_action :set_commercial, only: [:show, :edit, :update, :destroy]

  def index
      @commercials = Commercial.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
      @search = Commercial.search do
        fulltext params[:search_commercial_property]
        with(:property_post_type_id, params[:property_post_type]) if params[:property_post_type].present?
        with(:commercial_type_id, params[:commercial_type]) if params[:commercial_type].present?
        with(:price).between(params[:price_min]..params[:price_max]) if params[:price_min].present? or params[:price_ma].present?
        with(:size).between(params[:size_min]..params[:size_max]) if params[:size_min].present? or params[:size_max].present?
      end
      @search = Commercial.where(id: @search.results.map(&:id)).paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @commercial = Commercial.new
    property_location = @commercial.build_property_location
  end

  def edit
  end

  def create
    @commercial = Commercial.new(commercial_params)

    respond_to do |format|
      if @commercial.save
        gallery_images
        format.html { redirect_to @commercial, notice: 'Commercial was successfully created.' }
        format.json { render :show, status: :created, location: @commercial }
      else
        format.html { render :new }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @commercial.update(commercial_params)
        gallery_images
        format.html { redirect_to @commercial, notice: 'Commercial was successfully updated.' }
        format.json { render :show, status: :ok, location: @commercial }
      else
        format.html { render :edit }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @commercial.destroy
    respond_to do |format|
      format.html { redirect_to property_commercials_url, notice: 'Commercial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def gallery_images
        if  params[:property_galleries]['image'].each do |obj|
          @commercial.property_galleries.create!(image: obj)
        end
      end
    end

    def set_commercial
      @commercial = Commercial.find(params[:id])
    end

    def commercial_params
      params.require(:commercial).permit(
        :title, 
        :property_post_type_id, 
        :commercial_type_id, 
        :price, 
        :size, 
        :description, 
        property_galleries_attributes: [
          :id,
          :image  
        ],
        property_location_attributes: [
          :id,
          :address,
          :street,
          :city,
          :province,
          :country,
          :postal_code,
          :latitude,
          :longitude
        ]
      )
    end
end

app/controllers/property/premarket_styles_controller.rb
class Property::PremarketStylesController < ApplicationController
	before_action :set_premarket
	before_action :set_premarket_style, except: [:new, :create]

	def new
		@premarket_style = PremarketStyle.new
		@property_gallery = @premarket_style.property_galleries.build
	end

	def edit
	end

	def create
		@premarket_style = PremarketStyle.new(premarket_style_params)
		@premarket_style.premarket_id = params[:premarket_id]

		respond_to do |format|
			if @premarket_style.save
				gallery_images
				format.html { redirect_to premarket_url(@premarket), notice: "Premarket has been created" }
			else
				format.html { render :new }
			end
		end		
	end

	def update
		respond_to do |format|
			if @premarket_style.update(premarket_style_params)
				gallery_images
				format.html { redirect_to premarket_url(@premarket), notice: "Premarket has been updated"}
			else
				format.html { render :edit }
			end
		end
	end
	
	def destroy
		@premarket_style.destroy

		redirect_to do |format|
			format.html { redirect_to premarket_url(@premarket), notice: "Premarket has been deleted"}
		end
	end

	private

	    def gallery_images
      		params[:property_galleries]['image'].each do |obj|
				@premarket_style.property_galleries.create!(image: obj)
			end
	    end

		def set_premarket
			@premarket = Premarket.find(params[:premarket_id])
		end

		def set_premarket_style
			@premarket_style = @premarket.premarket_style.find(params[:id])
		end

		def premarket_style_params
			params.require(:premarket_style).permit(
				:premarket_id,
				:name,
				:price,
				:size,
				:description,
				:property_bedroom_id,
				:property_bathroom_id,
				:property_furnishing_type_id,
				:property_pet_friendly_type_id,
				:property_parking_space_id,
				{property_furniture_ids: []},
				{property_private_facility_ids: []},
				{property_area_ids: []},
				property_galleries_attributes: [
					:id,
					:image
				]
			)
		end
end

app/controllers/property/premarkets_controller.rb
class Property::PremarketsController < ApplicationController
  before_action :set_premarket, only: [:show, :edit, :update, :destroy]
  
  def index
      @premarkets = Premarket.all.order("created_at DESC")    
  end

  def show
  end

  def new
    @premarket = Premarket.new
    property_location = @premarket.build_property_location
    premarket_style = @premarket.premarket_styles.build
  end

  def edit
  end

  def create
    @premarket = Premarket.new(premarket_params)

    respond_to do |format|
      if @premarket.save
        format.html { redirect_to @premarket, notice: "Premarket has been created" }
      else
        format.html { render :new }
      end
    end

  end

  def update
    respond_to do |format|
      if @premarket.update(premarket_params)
        format.html { redirect_to @premarket, notice: "Premarket has been updated"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @premarket.destroy

    redirect_to do |format|
      format.html { redirect_to premarkets_url, notice: "Premarket has been deleted"}
    end
  end

  private

    def set_premarket
      @premarket = Premarket.find(params[:id])
    end

    def premarket_params
      params.require(:premarket).permit(
        :title,
        :premarket_type_id,
        :price,
        :description,
        :special_offer,
        :feature_image,
        {property_central_facility_ids: []},
        property_location_attributes: [
          :id,
          :address,
          :street,
          :city,
          :province,
          :country,
          :postal_code,
          :latitude,
          :longitude
        ]
      )
    end


end

app/controllers/property/residentials_controller.rb
class Property::ResidentialsController < ApplicationController
  before_action :set_residential, only: [:show, :edit, :update, :destroy]

  def index

    @residentials = Residential.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    @search = Residential.search do
      fulltext params[:search_residential_property]
      with(:property_post_type_id, params[:property_post_type]) if params[:property_post_type].present?
      with(:residential_type_id, params[:residential_type]) if params[:residential_type].present?
      with(:price).between(params[:price_min]..params[:price_max]) if params[:price_min].present? or params[:price_max].present?
      with(:size).between(params[:size_min]..params[:size_max]) if params[:size_min].present? or params[:size_max].present?
      with(:property_bedroom_id).between(params[:property_bedroom_min]..params[:property_bedroom_max]) if params[:property_bedroom_min].present? or params[:property_bedroom_max].present?
      with(:property_bathroom_id).between(params[:property_bathroom_min]..params[:property_bathroom_max]) if params[:property_bathroom_min].present? or params[:property_bathroom_max].present?
      with(:property_pet_friendly_type_id, params[:property_pet_friendly_type]) if params[:property_pet_friendly_type].present?
      with(:property_furnishing_type_id, params[:property_furnishing_type]) if params[:property_furnishing_type].present?
      with(:property_parking_space_id, params[:property_parking_space]) if params[:property_parking_space].present?
      with(:property_central_facility_ids).any_of(params[[:central_facility]]) if params[:central_facility].present?
    end
    @residentials = Residential.where(id: @search.results.map(&:id)).paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @residential = Residential.new
    property_location = @residential.build_property_location
  end

  def edit
  end

  def create
    @residential = Residential.new(residential_params)

    respond_to do |format|
      if @residential.save
        gallery_images
        format.html { redirect_to @residential, notice: 'Residential was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @residential.update(residential_params)
        gallery_images
        format.html { redirect_to @residential, notice: 'Residential was successfully updated.' }
        format.json { render :show, status: :ok, location: @residential }
      else
        format.html { render :edit }
        format.json { render json: @residential.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @residential.destroy
    respond_to do |format|
      format.html { redirect_to residentials_url, notice: 'Residential was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def gallery_images
        if  params[:property_galleries]['image'].each do |obj|
          @residential.property_galleries.create!(image: obj)
        end
      end
    end

    def set_residential
      @residential = Residential.find(params[:id])
    end

    def residential_params
      params.require(:residential).permit(
        :title,
        :residential_type_id,
        :property_post_type_id,
        :price,
        :size,
        :description,
        :property_bedroom_id,
        :property_bathroom_id,
        :property_furnishing_type_id,
        :property_pet_friendly_type_id,
        :property_parking_space_id,
        {property_central_facility_ids: []},
        {property_private_facility_ids: []},
        {property_furniture_ids: []},
        {property_area_ids: []},
        property_galleries_attributes: [
          :id,
          :image,
          :_destroy
        ],
        property_location_attributes: [
          :id,
          :address,
          :street,
          :city,
          :province,
          :country,
          :postal_code,
          :latitude,
          :longitude
        ]
      )
    end
end

app/helpers/property/commercials_helper.rb
module Property::CommercialsHelper
end

app/helpers/property/premarket_styles_helper.rb
module Property::PremarketStylesHelper
end

app/helpers/property/premarkets_helper.rb
module Property::PremarketsHelper
end

app/helpers/property/residentials_helper.rb
module Property::ResidentialsHelper
end

app/views/property/commercials/_form.html.erb
<%= simple_form_for(@commercial) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.association :property_post_type, selected: 1 %>
    <%= f.association :commercial_type, selected: 1 %>
    <%= f.input :price %>
    <%= f.input :size %>
    <%= f.input :description %>
    <%= f.file_field :property_galleries, multiple: true, name: "property_galleries[image][]" %>
  </div>

  <%= f.simple_fields_for :property_location do |f| %>
    <% render 'property/location_form', f: f %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/property/commercials/_search_filter.html.erb
<h1>Filter Search</h1>
<%= form_tag residentials_path, method: :get do %>

  <div class="row">
    <h2 class="filter-section-header">Type:</h2>
    <div class="small-6 medium-6 large-6 columns">
      <%= select_tag :property_post_type, options_from_collection_for_select(PropertyPostType.all, :id, :name, params[:property_post_type]), include_blank: "Post Type" %> 
      <!-- Use  params[:field_name] just to persist the value -->
    </div>
    <div class="small-6 medium-6 large-6 columns">
      <%= select_tag :commercial_type, options_from_collection_for_select(CommercialType.all, :id, :name), include_blank: "Residential Type" %> 
    </div>     
  </div>

  <div class="row">
    <h2 class="filter-section-header">Details:</h2>
  </div>


  <div class="row collapse">
    <label>Price</label>    
    <div class="small-5 medium-5 large-5 columns">
      <%= number_field_tag :price_min, params[:price_min], placeholder: "Min." %>
    </div>
    <div class="small-1 medium-1 large-1 columns">
      <span class="postfix">-</span>
    </div>
    <div class="small-6 medium-6 large-6 columns"> 
      <%= number_field_tag :price_max, params[:price_max], placeholder: "Max." %>
    </div>  
    <hr>      
  
    <label>Size</label>
    <div class="small-5 medium-5 large-5 columns">
      <%= number_field_tag :size_min, params[:size_min], placeholder: "Min." %>
    </div>
    <div class="small-1 medium-1 large-1 columns">
      <span class="postfix">-</span>
    </div>
    <div class="small-6 medium-6 large-6 columns">
      <%= number_field_tag :size_max, params[:size_max], placeholder: "Max." %>
    </div>
    <hr>

  <div class="row">
    <%= submit_tag "Filter", name: nil, :class => "button" %>
  </div>
<% end %>

app/views/property/commercials/_search_fulltext.html.erb
<%= form_tag residentials_path, method: :get do %>
  <div class="row collapse">
    <div class="small-10 columns">
      <%= text_field_tag :search_commercial_property, params[:search_commercial_property], placeholder: "Search with keyword" %>
    </div>
    <div class="small-2 columns">
      <%= submit_tag "Search", name: nil, class: "button postfix" %>
    </div>
  </div> 
<% end %>

app/views/property/commercials/edit.html.erb
<h1>Editing Commercial</h1>

<%= render 'form' %>

<%= link_to 'Show', @commercial %> |
<%= link_to 'Back', commercials_path %>

app/views/property/commercials/index.html.erb
<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <div class="panel radius">
      <%= render 'search_fulltext' %>
    </div>  
  </div>

  <div class="small-12 medium-4 large-3 columns">
    <div class="filter-search-form small-12 medium-12 large-12 columns">
      <%= render 'search_filter' %>
    </div>
  </div>
  </div>

  <div class="small-12 medium-8 large-9 columns">
    <h1>Listing Commercials</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Postable</th>
          <th>Commercial type</th>
          <th>Price</th>
          <th>Size</th>
          <th>Description</th>
          <th>Imageable</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @commercials.each do |commercial| %>
          <tr>
            <td><%= commercial.title %></td>
            <td><%= commercial.property_post_type.name %></td>
            <td><%= commercial.commercial_type.name %></td>
            <td><%= commercial.price %></td>
            <td><%= commercial.size %></td>
            <td><%= commercial.description %></td>
            <td><%= link_to 'Show', commercial %></td>
            <td><%= link_to 'Edit', edit_commercial_path(commercial) %></td>
            <td><%= link_to 'Destroy', commercial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Commercial', new_commercial_path %>

  </div>

</div>


    

app/views/property/commercials/new.html.erb
<h1>New Commercial</h1>

<%= render 'form' %>

<%= link_to 'Back', commercials_path %>

app/views/property/commercials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @commercial.title %>
</p>

<p>
  <strong>Postable:</strong>
  <%= @commercial.property_post_type.name %>
</p>

<p>
  <strong>Commercial type:</strong>
  <%= @commercial.commercial_type.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @commercial.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @commercial.size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @commercial.description %>
</p>

<p>
  <strong>Locations:</strong>
  <%= @commercial.property_location.address %>
  <%= @commercial.property_location.street %>
  <%= @commercial.property_location.city %>
  <%= @commercial.property_location.province %>
  <%= @commercial.property_location.country %>
  <%= @commercial.property_location.postal_code %>
</p>

<p>
  <strong>Gallery:</strong>
  <% @commercial.property_galleries.each do |obj| %>
    <%= image_tag obj.image.url(:thumb).to_s %>
  <% end %>
</p>

<%= link_to 'Edit', edit_commercial_path(@commercial) %> |
<%= link_to 'Back', commercials_path %>