config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'account'
  
  resources :users do
    scope module: 'user' do
      resources :profiles
    end  
  end

  scope module: 'property' do
    resources :commercials
    resources :residentials
    resources :premarkets do
      resources :premarket_styles
    end
  end

  resources :posts

  resources :statics do
    collection do
      get 'homepage'
    end
  end

  root 'statics#homepage'

end

app/models/commercial.rb
class Commercial < ActiveRecord::Base
  belongs_to :commercial_type
  belongs_to :property_post_type
  has_many :property_galleries, as: :imageable
  has_one :property_location, as: :locatable

  accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :property_location

  # Sunspot search function
  searchable do
  	text :title, :description
  	integer :property_post_type_id
  	integer :commercial_type_id
  	double :price
  	double :size
  end
end

app/models/commercial_type.rb
class CommercialType < ActiveRecord::Base
	has_many :commercials
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :post_categorizations
	has_many :post_categories, through: :post_categorizations

	mount_uploader :feature_image, PostFeatureImageUploader

	# Search function
	searchable do 
		text :title, :excerpt, :content
		integer :post_category_ids, :multiple => true
	end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	has_many :post_categorizations
	has_many :posts, through: :post_categorizations
end

app/models/premarket.rb
class Premarket < ActiveRecord::Base
	belongs_to :premarket_type
	
	has_many :premarket_styles, dependent: :destroy
	has_many :property_central_facilities, as: :central_facility
	has_one :property_location, as: :locatable

  accepts_nested_attributes_for :property_location
	accepts_nested_attributes_for :premarket_styles, reject_if: :all_blank, allow_destroy: :true 

	mount_uploader :feature_image, PremarketFeatureImageUploader
end

app/models/premarket_style.rb
class PremarketStyle < ActiveRecord::Base
	belongs_to :premarket

	belongs_to :property_bedroom
	belongs_to :property_bathroom
	belongs_to :property_furnishing_type
	belongs_to :property_pet_friendly_type
	belongs_to :property_parking_space
	has_many :property_private_facilities, as: :private_facility
	has_many :property_furnitures, as: :furniture
	has_many :property_areas, as: :area
	has_many :property_galleries, as: :imageable, dependent: :destroy

	accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true 
end

app/models/premarket_type.rb
class PremarketType < ActiveRecord::Base
	has_one :premarket
end

app/models/property_area.rb
class PropertyArea < ActiveRecord::Base
	belongs_to :area, polymorphic: true
end

app/models/property_bathroom.rb
class PropertyBathroom < ActiveRecord::Base
	has_one :residential
	has_one :premarket_style
end

app/models/property_bedroom.rb
class PropertyBedroom < ActiveRecord::Base
	has_one :residential
	has_one :premarket_style
end

app/models/property_gallery.rb
class PropertyGallery < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true

	mount_uploader :image, PropertyGalleryUploader
end

app/models/property_location.rb
class PropertyLocation < ActiveRecord::Base
	belongs_to :locatable, polymorphic: true
end

app/models/residential.rb
class Residential < ActiveRecord::Base
  has_many :property_central_facilities, as: :central_facility
  has_many :property_private_facilities, as: :private_facility
  has_many :property_furnitures, as: :furniture
  has_many :property_areas, as: :area
  has_many :property_galleries, as: :imageable
  has_one :property_location, as: :locatable
  belongs_to :property_post_type
  belongs_to :residential_type
  belongs_to :property_bedroom
  belongs_to :property_bathroom
  belongs_to :property_furnishing_type
  belongs_to :property_pet_friendly_type
  belongs_to :property_parking_space

  accepts_nested_attributes_for :property_galleries, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :property_location
  
  # Sunspot search function
  searchable do
    text :title, :description
    integer :residential_type_id 
    integer :property_post_type_id
    integer :property_bedroom_id
    integer :property_bathroom_id
    integer :property_furnishing_type_id
    integer :property_pet_friendly_type_id
    integer :property_parking_space_id
    integer :property_central_facility_ids, :multiple => true
    # integer :private_facility, :multiple => true
    # integer :furniture, :multiple => true
    # integer :area,  :multiple => true
    double :price
    double :size
  end
end

app/models/residential_type.rb
class ResidentialType < ActiveRecord::Base
	has_many :residentials
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile
end

app/models/user_company.rb
class UserCompany < ActiveRecord::Base
  belongs_to :user_profession
end

app/models/user_profession.rb
class UserProfession < ActiveRecord::Base
	belongs_to :user_profile
	has_one :user_company
	belongs_to :user_professional_expertise

	accepts_nested_attributes_for :user_company, reject_if: :all_blank
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user
	has_one :user_profession

	accepts_nested_attributes_for :user_profession, reject_if: :all_blank 
	
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_category
		@post_categories = PostCategory.all
	end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="small-12 medium-12 large-12 columns">
			<div class="small-6 medium-4 large-3 columns">
				<p class="section-header">Cards</p>
				<ul>
					<li><%= link_to "link 1", residentials_path %></li>
					<li><%= link_to "link 2", residentials_path %></li>
					<li><%= link_to "link 3", residentials_path %></li>
					<li><%= link_to "link 4", residentials_path %></li>
					<li><%= link_to "link 5", residentials_path %></li>
				</ul>
			</div>
			<div class="small-6 medium-4 large-3 columns">
				<p class="section-header">Loans</p>
				<ul>
					<li><%= link_to "link 1", residentials_path %></li>
					<li><%= link_to "link 2", residentials_path %></li>
					<li><%= link_to "link 3", residentials_path %></li>
					<li><%= link_to "link 4", residentials_path %></li>
					<li><%= link_to "link 5", residentials_path %></li>
				</ul>
			</div>
			<div class="small-6 medium-4 large-3 columns">
				<p class="section-header">Updates</p>
				<ul>
					<li><%= link_to "link 1", residentials_path %></li>
					<li><%= link_to "link 2", residentials_path %></li>
					<li><%= link_to "link 3", residentials_path %></li>
					<li><%= link_to "link 4", residentials_path %></li>
					<li><%= link_to "link 5", residentials_path %></li>
				</ul>
			</div>
			<div class="small-6 medium-4 large-3 columns end">
				<p class="section-header">Others</p>
				<ul>
					<li><%= link_to "link 1", residentials_path %></li>
					<li><%= link_to "link 2", residentials_path %></li>
					<li><%= link_to "link 3", residentials_path %></li>
					<li><%= link_to "link 4", residentials_path %></li>
					<li><%= link_to "link 5", residentials_path %></li>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Estateer.com", root_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
          <li class="has-dropdown">
            <%= link_to current_user.email %>
            <ul class="dropdown">
              <% if UserProfile.where(user_id: current_user.id).any? %>
                <li><%= link_to 'My Profile', user_profile_path([@user, current_user], [current_user] ) %></li>
              <% else %>
                <li><%= link_to 'Create Profile', new_user_profile_path(user_id: current_user) %></li>
              <% end %>  
              <li><%= link_to "Account Setting", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Signup", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-dropdown">
          <%= link_to "Residential Property", residentials_path %>
          <ul class="dropdown">
            
            <li><%= link_to "Browse All", residentials_path %></li>

            <li><label>Post Type:</label></li>
            <% PropertyPostType.all.each do |pt| %>
              <li><%= link_to pt.name, residentials_path(property_post_type: pt.name) %></li>
            <% end %>

            <li><label>Property Type:</label></li>
            <% ResidentialType.all.each do |rt| %>
              <li><%= link_to rt.name, residentials_path(residential_type: rt.name) %></li>
            <% end %>

          </ul>
        </li>

        <li class="has-dropdown">
          <%= link_to "Commercial Property", commercials_path %>
          <ul class="dropdown">
            <li><%= link_to "Commercial Property", commercials_path %></li>

            <li><label>Post Type:</label></li>
            <% PropertyPostType.all.each do |pt| %>
              <li><%= link_to pt.name, commercials_path(property_post_type: pt.name) %></li>
            <% end %>
            
            <li><label>Property Type:</label></li>
            <% CommercialType.all.each do |ct| %>
              <li><%= link_to ct.name, commercials_path(commercial_type: ct.name) %></li>
            <% end %>
          </ul>  
        </li>

        <li class="has-dropdown">
          <%= link_to "Premarket Property", premarkets_path %>
          <ul class="dropdown">

            <% PremarketType.all.each do |pmt| %>
              <li><%= link_to pmt.name, premarkets_path(premarket_type: pmt.name) %></li>
            <% end %>
          </ul>  
        </li>

        <li><a href="#">Find Agent</a></li> 
        <li><a href="#">Find Service</a></li> 

        <li class="has-dropdown">
          <%= link_to "Updates", posts_path %>
          <ul class="dropdown">

            <% PostCategory.all.each do |pc| %>
              <li><%= link_to pc.name, posts_path(post_category: pc.name) %></li>
            <% end %>
          </ul>  
        </li>
      </ul>
    </section>
  </nav>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Estateer: Home, Apartment, Condo, office and all real estate properties for Rent & Sell " %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar'%>
    

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>